name: 自动编译 SCSS 为 CSS
on:
  push:
    paths:
      - '**.scss'  # 仅当 SCSS 文件被推送时触发
    branches: [ main ]  # 监听 main 分支

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码
      - name:  checkout 代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # 使用配置的令牌

      # 2. 安装 Node.js（用于运行 sass 编译工具）
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # 指定 Node 版本

      # 3. 安装 sass 编译工具
      - name: 安装 sass
        run: npm install -g sass  # 全局安装 sass

      # 4. 编译 SCSS 为 CSS
      - name: 编译 SCSS
        run: |
          # 示例：将 src/scss 目录下的所有 SCSS 编译到 dist/css
          # --style compressed 表示压缩输出，可改为 expanded（未压缩）
          sass src/scss:dist/css --style compressed

      # 5. 提交编译后的 CSS 到仓库
      - name: 提交 CSS 文件
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/css  # 添加编译后的 CSS 目录
          git commit -m "Auto-compile SCSS to CSS" || echo "No changes to commit"
          git push origin main