name: 自动编译 SCSS 为 CSS
on:
  push:
    paths:
      - '**.scss'  # 仅当 SCSS 文件变更时触发
    branches: [ main ]  # 监听 main 分支（若你的默认分支是 master，改为 master）

jobs:
  compile-scss:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 服务器
    steps:
      # 步骤 1：拉取仓库代码到服务器
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # 后续配置的令牌

      # 步骤 2：安装 Node.js（Sass 依赖 Node 环境）
      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # 推荐 18.x 及以上版本

      # 步骤 3：安装 Sass 编译工具
      - name: 安装 Sass
        run: npm install -g sass  # 全局安装 Sass

      # 步骤 4：编译 SCSS 为 CSS（核心步骤，需修改路径）
      - name: 编译 SCSS
        run: |
          # 格式：sass 源目录:输出目录 --style 编译格式
          # 示例：将 src/scss 下的所有 SCSS 编译到 dist/css
          sass src/scss:dist/css --style expanded  # expanded 为未压缩格式，可选 compressed（压缩）

      # 步骤 5：将编译后的 CSS 提交回仓库
      - name: 提交 CSS 文件
        run: |
          git config --global user.name "GitHub Actions"  # 提交者名称
          git config --global user.email "actions@github.com"  # 提交者邮箱
          git add dist/css  # 添加编译后的 CSS 目录（根据实际输出目录修改）
          git commit -m "自动编译 SCSS 为 CSS" || echo "无新内容需提交"
          git push origin main  # 推送到 main 分支（与 on.branches 保持一致）